# config file version
apiVersion: 1

# list of datasources to insert/update
datasources:
  # <string, required> name of the datasource. Required
- name: MSSQL
  # <string, required> datasource type. Required
  type: mssql
  # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
  access: proxy
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> custom UID which can be used to reference this datasource in other parts of the configuration, if not specified will be generated automatically
  # uid: my_unique_uid
  # <string> url
  url: mssql
  user: SA
  # <string> database name
  database: ExampleDB
  # <bool> allow updating provisioned dashboards from the UI
  allowUiUpdates: true
  # <bool> mark as default datasource. Max one per org
  isDefault: true
  # <map> fields that will be converted to json and stored in jsonData
  jsonData:
    authenticationType: "SQL Server Authentication"
    encrypt: "false"
  secureJsonData:
    # <string> database password, if used
    password: "?Super3Secure2Password1!"
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: true