{
 "title": "Umati machine data",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": {
    "content": "<center>\n<div>\n  <a href=\"https://opc-router.com/?utm_source=GitHub&utm_medium=DockerSample&utm_campaign=OpcUaUmatiMssqlGrafana\">\n    <img src=\"https://www.opc-router.de/wp-content/uploads/2019/08/opc-router-logo-2x-400x108.png\" alt=\"Logo\" >\n  </a>\n    <br />\n    <br />\n</div>"
   }
  },
  {
   "title": "Actual Cycle",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n\t\t[ActualCycle]\nFROM\n  MachineProductivity"
    }
   ]
  },
  {
   "title": "Actual Cycle",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT \n  $__timeEpoch(timestamp),\n\t\t[ActualCycle]\nFROM\n  MachineProductivity\nWHERE\n  $__timeFilter(timestamp)\nORDER BY\n  timestamp ASC"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n\t\t[RunsPlanned],\n\t\t[RunsCompleted]\nFROM\n  MachineProductivity"
    }
   ]
  },
  {
   "title": "Working Time (hh:mm:ss)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n\t\t[workingTime]\nFROM\n  MachineStatus"
    }
   ]
  },
  {
   "title": "Calibrated",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\t\t[Calibrated]\nFROM\n  MachineStatus"
    }
   ]
  },
  {
   "title": "Moving",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\t\t[Moving]\nFROM\n  MachineStatus"
    }
   ]
  },
  {
   "title": "Warning",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\t\t[Warning]\nFROM\n  MachineStatus"
    }
   ]
  },
  {
   "title": "Recipe in Run",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n\t\t[RecipeInRun]\nFROM\n  MachineStatus"
    }
   ]
  },
  {
   "title": "Stacklight Transport",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n\t\t[currentState]\nFROM\n  MachineStatus"
    }
   ]
  },
  {
   "title": "Absolute Pieces In",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n\t\t[AbsolutePiecesIn]\nFROM\n  MachineProductivity"
    }
   ]
  },
  {
   "title": "Alarm",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\t\t[Alarm]\nFROM\n  MachineStatus"
    }
   ]
  },
  {
   "title": "Machine On",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\t\t[MachineOn]\nFROM\n  MachineStatus"
    }
   ]
  },
  {
   "title": "Feed Speed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n\t\t[FeedSpeed]\nFROM\n  MachineProductivity"
    }
   ]
  },
  {
   "title": "Absolute Pieces Out",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n\t\t[AbsolutePiecesOut]\nFROM\n  MachineProductivity"
    }
   ]
  },
  {
   "title": "Device Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n\t\t[SignalLamp1],\n\t\t[SignalLamp2],\n\t\t[SignalLamp3]\nFROM\n  MachineStatus"
    }
   ]
  }
 ]
}